#include <fstream>
#include <iostream>
#include <string>
#include "TFile.h"

void parseVersion(std::string version, std::string& v, std::string& r,
                  std::string& p) {
  int vloc = version.find("v");
  int rloc = version.find("r");
  int ploc = version.find("p");
  int size = version.length();

  if (vloc == std::string::npos) {
    std::cerr << "WARNING: SoftwareVersion " << version
              << " is not a valid format!" << std::endl;
    exit(3);
  }
  if (rloc == std::string::npos) {
    // vX
    v = version.substr(++vloc, size - vloc);
    r = "0";
    p = "0";
  } else if (ploc == std::string::npos) {
    // vXrY
    v = version.substr(++vloc, rloc - vloc);
    r = version.substr(++rloc, size - rloc);
    p = "0";
  } else {
    // vXrYpZ
    v = version.substr(++vloc, rloc - vloc);
    r = version.substr(++rloc, ploc - rloc);
    p = version.substr(++ploc, size - ploc);
  }
}

void exportVersion(char const* inpHeaderLoc = NULL) {
  TFile* inputFile;

  char* path = NULL;
  path = getenv("PWD");
  strcat(path, "/input-file.list");

  if (!getenv("ND280ANALYSISTOOLSROOT") ||
      !getenv("ND280ANALYSISTOOLSCONFIG")) {
    std::cout << "[ERROR]: ENV vars ND280ANALYSISTOOLSROOT and "
                 "ND280ANALYSISTOOLSCONFIG are not defined."
              << std::endl;
  }

  std::string libReadHeaderLocation = "";
  if (inpHeaderLoc) {
    libReadHeaderLocation = inpHeaderLoc;
  } else {
    libReadHeaderLocation = getenv("ND280ANALYSISTOOLSROOT");
    libReadHeaderLocation +=
        "/" + std::string(getenv("ND280ANALYSISTOOLSCONFIG")) +
        "/AnalysisTools/libReadoaAnalysis/libReadoaAnalysisProjectHeaders.h";
  }

  std::ofstream out(libReadHeaderLocation.c_str(), std::ofstream::app);
  std::cout << "Writing version information to " << libReadHeaderLocation
            << std::endl;

  ifstream in(path);
  if (!in || in.bad()) return;

  std::string file;
  while (!in.eof()) {
    in >> file;
    if (file.find("break") != std::string::npos) {
      std::cout << "Hit 'break' without finding a valid file" << std::endl;
      return;
    }
    std::cout << "Trying: " << file << std::endl;
    inputFile = TFile::Open(file.c_str());
    if (inputFile) break;
  }
  in.close();

  if (!inputFile) std::cout << "File open failed" << std::endl;

  TTree* tree = (TTree*)inputFile->Get("HeaderDir/BasicHeader");
  if (!tree) {
    std::cerr << "*************************************************************"
                 "*****************"
              << std::endl;
    std::cerr << "* WARNING: input file doesn't contain HeadeDir/BasicHeader "
                 "tree!             *"
              << std::endl;
    std::cerr << "* Pre-processor variables cannot be set!                     "
                 "                *"
              << std::endl;
    std::cerr << "*************************************************************"
                 "*****************"
              << std::endl;
    exit(1);
  }

  char version[50];
  tree->SetBranchAddress("SoftwareVersion", &version);
  tree->GetEntry(0);

  if (!strcmp(version, "") || !strcmp(version, "NULL")) {
    std::cerr << "*************************************************************"
                 "*****************"
              << std::endl;
    std::cerr << "* WARNING: Your oaAnalysis file does not say which "
                 "SoftwareVersion was used! *"
              << std::endl;
    std::cerr << "* >>>>>>>>> IF YOU ARE USING HIGHLAND, THEN THIS MAY BE A "
                 "PROBLEM! <<<<<<<<< *"
              << std::endl;
    std::cerr << "* If you created the file yourself, please re-run oaAnalysis "
                 "with the        *"
              << std::endl;
    std::cerr << "* -O TBasicHeaderModule=software_version option enabled.     "
                 "                *"
              << std::endl;
    std::cerr << "*************************************************************"
                 "*****************"
              << std::endl;
    exit(2);
  }

  std::string v = "";
  std::string r = "";
  std::string p = "";
  parseVersion(version, v, r, p);

  out << "/* Version information autogenerated by exportVersion.C */"
      << std::endl;
  out << "#ifndef ANATOOLS_FILE_VERSION" << std::endl;
  out << "#define ANATOOLS_FILE_VERSION \"" << version << "\"" << std::endl;
  out << "#define ANATOOLS_FILE_MAJOR_VERSION " << v << std::endl;
  out << "#define ANATOOLS_FILE_MINOR_VERSION " << r << std::endl;
  out << "#define ANATOOLS_FILE_PATCH_VERSION " << p << std::endl;
  out << "#define BEFORE_ANATOOLS_FILE(v,r,p) "
         "((ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION==(r)&"
         "&ANATOOLS_FILE_PATCH_VERSION<(p))||(ANATOOLS_FILE_MAJOR_VERSION==(v)&"
         "&ANATOOLS_FILE_MINOR_VERSION<(r))||(ANATOOLS_FILE_MAJOR_VERSION<(v)))"
      << std::endl;
  out << "#define EQUALS_ANATOOLS_FILE(v,r,p) "
         "(ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION==(r)&&"
         "ANATOOLS_FILE_PATCH_VERSION==(p))"
      << std::endl;
  out << "#define ANATOOLS_FILE_PROD5 BEFORE_ANATOOLS_FILE(11,0,0)"
      << std::endl;
  out << "#define ANATOOLS_FILE_AFTERPROD5 !BEFORE_ANATOOLS_FILE(11,0,0)"
      << std::endl;
  out << "#endif" << std::endl;

  out.close();

  std::cout << "[exportVersion.C]: Wrote versioning information!" << std::endl;

  gApplication->Terminate();
}
