//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Mar 20 17:07:53 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file /mnt/data/backup/production006/B/mcp/neut/2010-11-air/magnet/run4/anal/oa_nt_beam_90400000-0000_jrvqqzb53okw_anal_000_prod6amagnet201011airc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__ToaAnalysisUtils_h
#define ND__ToaAnalysisUtils_h
namespace ND {
class ToaAnalysisUtils;
} // end of namespace.

#include "TObject.h"

namespace ND {
class ToaAnalysisUtils : public TObject {

public:
// Nested classes forward declaration.
enum EParticleCategory { kDefault_EParticleCategory };
enum ESubdetector { kDefault_ESubdetector };

public:
// Nested classes declaration.

public:
// Data Members.

   ToaAnalysisUtils();
   ToaAnalysisUtils(const ToaAnalysisUtils & );
   virtual ~ToaAnalysisUtils();

   ClassDef(ToaAnalysisUtils,2); // Generated by MakeProject.
};
} // namespace
#endif
