//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Mar 20 17:07:53 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file /mnt/data/backup/production006/B/mcp/neut/2010-11-air/magnet/run4/anal/oa_nt_beam_90400000-0000_jrvqqzb53okw_anal_000_prod6amagnet201011airc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisTruthModuleBase_h
#define ND__TAnalysisTruthModuleBase_h
namespace ND {
class TAnalysisTruthModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisTruthModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisTruthModuleBase();
   TAnalysisTruthModuleBase(const TAnalysisTruthModuleBase & );
   virtual ~TAnalysisTruthModuleBase();

   ClassDef(TAnalysisTruthModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
