//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Mar 20 17:07:54 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file /mnt/data/backup/production006/B/mcp/neut/2010-11-air/magnet/run4/anal/oa_nt_beam_90400000-0000_jrvqqzb53okw_anal_000_prod6amagnet201011airc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TRooTrackerVtxModuleBase_h
#define ND__TRooTrackerVtxModuleBase_h
namespace ND {
class TRooTrackerVtxModuleBase;
} // end of namespace.

#include "ND__TAnalysisTruthModuleBase.h"
#include "TClonesArray.h"

namespace ND {
class TRooTrackerVtxModuleBase : public ND::TAnalysisTruthModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       fNVtx;       ///< The number of vertices
   TClonesArray* fVtx;        ///< TClonesArray of vertex objects 
   bool          fPassThroughPresent;    //

   TRooTrackerVtxModuleBase();
   TRooTrackerVtxModuleBase(const TRooTrackerVtxModuleBase & );
   virtual ~TRooTrackerVtxModuleBase();

   ClassDef(TRooTrackerVtxModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
